USE tempdb;
IF(db_id('PlanesCoreGDB') IS NOT NULL)
EXEC('
ALTER DATABASE PlanesCoreGDB SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE;
USE PlanesCoreGDB;
ALTER DATABASE PlanesCoreGDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
USE tempdb;
DROP DATABASE PlanesCoreGDB;
');

CREATE DATABASE PlanesCoreGDB WITH TRUSTWORTHY ON;
GO
USE PlanesCoreGDB;
GO
